/// https://developer.mozilla.org/en-US/docs/Web/HTTP/Reference/Status
pub const Code = enum(u10) {
    // Informational
    @"continue" = 100,
    switchingProtocols = 101,
    processing = 102,
    earlyHints = 103,
    // Successful
    ok = 200,
    created = 201,
    accepted = 202,
    nonAuthoritativeInformation = 203,
    noContent = 204,
    resetContent = 205,
    partialContent = 206,
    multiStatus = 207,
    alreadyReported = 208,
    imUsed = 226,
    // Redirections
    multipleChoices = 300,
    movedPermanently = 301,
    found = 302,
    seeOther = 303,
    notModified = 304,
    useProxy = 305,
    unused = 306,
    temporaryRedirect = 307,
    permanentRedirect = 308,
    // Client error
    badRequest = 400,
    unauthorized = 401,
    paymentRequired = 402,
    forbidden = 403,
    notFound = 404,
    methodNotAllowed = 405,
    notAcceptable = 406,
    proxyAuthenticationRequired = 407,
    requestTimeout = 408,
    conflict = 409,
    gone = 410,
    lengthRequired = 411,
    preconditionFailed = 412,
    contentTooLarge = 413,
    uriTooLong = 414,
    unsupportedMediaType = 415,
    rangeNotSatisfiable = 416,
    expectationFailed = 417,
    imaTeapot = 418,
    misdirectedRequest = 421,
    unprocessableContent = 422,
    locked = 423,
    failedDependency = 424,
    tooEarly = 425,
    upgradeRequired = 426,
    preconditionRequired = 428,
    tooManyRequests = 429,
    requestHeaderFieldsTooLarge = 431,
    unavailableForLegalReasons = 451,
    // Server error
    internalServerError = 500,
    notImplemented = 501,
    badGateway = 502,
    serviceUnavailable = 503,
    gatewayTimeout = 504,
    httpVersionNotSupported = 505,
    variantAlsoNegotiates = 506,
    insufficientStorage = 507,
    loopDetected = 508,
    notExtended = 510,
    networkAuthenticationRequired = 511,
};

pub fn message(code: Code) []const u8 {
    return switch (code) {
        // Informational
        .@"continue" => "Continue",
        .switchingProtocols => "Switching Protocols",
        .processing => "Processing",
        .earlyHints => "Early Hints",
        // Successful
        .ok => "OK",
        .created => "Created",
        .accepted => "Accepted",
        .nonAuthoritativeInformation => "Non-Authoritative Information",
        .noContent => "No Content",
        .resetContent => "Reset Content",
        .partialContent => "Partial Content",
        .multiStatus => "Multi-Status",
        .alreadyReported => "Already Reported",
        .imUsed => "IM Used",
        // Redirections
        .multipleChoices => "Multiple Choices",
        .movedPermanently => "Moved Permanently",
        .found => "Found",
        .seeOther => "See Other",
        .notModified => "Not Modified",
        .useProxy => "Use Proxy",
        .unused => "Unused",
        .temporaryRedirect => "Temporary Redirect",
        .permanentRedirect => "Permanent Redirect",
        // Client error
        .badRequest => "Bad Request",
        .unauthorized => "Unauthorized",
        .paymentRequired => "Payment Required",
        .forbidden => "Forbidden",
        .notFound => "Not Found",
        .methodNotAllowed => "Method Not Allowed",
        .notAcceptable => "Not Acceptable",
        .proxyAuthenticationRequired => "Proxy Authentication Required",
        .requestTimeout => "Request Timeout",
        .conflict => "Conflict",
        .gone => "Gone",
        .lengthRequired => "Length Required",
        .preconditionFailed => "Precondition Failed",
        .contentTooLarge => "Content Too Large",
        .uriTooLong => "URI Too Long",
        .unsupportedMediaType => "Unsupported Media Type",
        .rangeNotSatisfiable => "Range Not Satisfied",
        .expectationFailed => "Expectation Failed",
        .imaTeapot => "I'm a teapot",
        .misdirectedRequest => "Misdirected Request",
        .unprocessableContent => "Unprocessable Content",
        .locked => "Locked",
        .failedDependency => "Failed Dependency",
        .tooEarly => "Too Early",
        .upgradeRequired => "Upgrade Required",
        .preconditionRequired => "Precondition Required",
        .tooManyRequests => "Too Many Requests",
        .requestHeaderFieldsTooLarge => "Request Header Fields Too Large",
        .unavailableForLegalReasons => "Unavailable For Legal Reasons",
        // Server error
        .internalServerError => "Internal Server Error",
        .notImplemented => "Not Implemented",
        .badGateway => "Bad Gateway",
        .serviceUnavailable => "Service Unavailable",
        .gatewayTimeout => "Gateway Timeout",
        .httpVersionNotSupported => "HTTP Version Not Supported",
        .variantAlsoNegotiates => "Variant Also Negotiates",
        .insufficientStorage => "Insufficient Storage",
        .loopDetected => "Loop Detected",
        .notExtended => "Not Extended",
        .networkAuthenticationRequired => "Network Authentication Required",
    };
}
